// Export all services from a single entry point
export { default as api, setAuthHeader, clearAuthHeader, getAuthToken, isAuthenticated, getApiBaseUrl } from './api';
export { default as authService } from './authService';
export { default as courseService } from './courseService';
export { default as enrollmentService } from './enrollmentService';
export { default as videoService } from './videoService';
export { default as certificateService } from './certificateService';
export { default as certificateTemplateService, CERTIFICATE_TYPES } from './certificateTemplateService';
export { default as blogService } from './blogService';
export { default as adminService } from './adminService';
export { default as configService } from './configService';
export { default as masterDataService, DATA_TYPES } from './masterDataService';
export { default as faqService } from './faqService';
export { default as reviewService } from './reviewService';
export { default as serviceCertificationService } from './serviceCertificationService';
export { default as serviceTestingService } from './serviceTestingService';
export { default as serviceDiagnosticsService } from './serviceDiagnosticsService';
export { default as careerService } from './careerService';
export { default as bundleService } from './bundleService';
export { flagshipService } from './flagshipService';
export { default as marketingService } from './marketingService';
export { default as standardsService } from './standardsService';
