ALTER TABLE course ADD COLUMN IF NOT EXISTS key_components TEXT;
ALTER TABLE course ADD COLUMN IF NOT EXISTS target_audience TEXT;
ALTER TABLE course ADD COLUMN IF NOT EXISTS assessment TEXT;
ALTER TABLE course ADD COLUMN IF NOT EXISTS outcome TEXT;
ALTER TABLE course ADD COLUMN IF NOT EXISTS course_duration_text TEXT;
ALTER TABLE course ADD COLUMN IF NOT EXISTS exam_details TEXT;
