ALTER TABLE users ADD COLUMN IF NOT EXISTS email_bounced BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_bounced_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_bounce_type VARCHAR(50);
